"""
Django settings for yamdb project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(dotenv_path=os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(key="SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv(key="DEBUG", default="False") == "True"

ALLOWED_HOSTS = os.getenv(key="ALLOWED_HOSTS", default="").split(sep=",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "django_filters",
    "drf_spectacular",
    "users.apps.UsersConfig",
    "reviews.apps.ReviewsConfig",
    "api.apps.ApiConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "yamdb.urls"

TEMPLATES_DIR = os.path.join(BASE_DIR, "templates")
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [TEMPLATES_DIR],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "yamdb.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ru-RU"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = (os.path.join(BASE_DIR, "static/"),)

AUTH_USER_MODEL = "users.User"

DEFAULT_FROM_EMAIL = "noreply@yamdb.com"

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"

EMAIL_FILE_PATH = os.path.join(BASE_DIR, "sent_emails")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "YaMDb API",
    "DESCRIPTION": "Документация к API проекта YaMDb",
    "VERSION": "v1",
    "CONTACT": {
        "email": "admin@yamdb.ru",
    },
    "LICENSE": {
        "name": "MIT License",
    },
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
    "TAGS": [
        {
            "name": "Описание",
            "description": (
                "Проект <b>YaMDb</b> собирает отзывы пользователей на различные произведения."
            ),
        },
        {
            "name": "Алгоритм регистрации пользователей",
            "description": (
                "<ol><li>Пользователь отправляет POST-запрос на добавление нового пользователя с "
                "параметрами <code>email</code> и <code>username</code> на эндпоинт "
                "<code>/api/v1/auth/signup/</code>.</li>"
                "<li><b>YaMDB</b> отправляет письмо с кодом подтверждения (<code>confirmation_code"
                "</code>) на адрес <code>email</code>.</li>"
                "<li>Пользователь отправляет POST-запрос с параметрами <code>username</code> и "
                "<code>confirmation_code</code> на эндпоинт <code>/api/v1/auth/token/</code>, в "
                "ответе на запрос ему приходит <code>token</code> (JWT-токен).</li>"
                "<li>При желании пользователь отправляет PATCH-запрос на эндпоинт "
                "<code>/api/v1/users/me/</code> и заполняет поля в своём профайле (описание полей "
                "— в документации).</li></ol>"
            ),
        },
        {
            "name": "Пользовательские роли",
            "description": (
                "<ul><li><b>Аноним</b> — может просматривать описания произведений, читать отзывы "
                "и комментарии.</li>"
                "<li><b>Аутентифицированный пользователь</b> (<code>user</code>) — может, как и "
                "<b>Аноним</b>, читать всё, дополнительно он может публиковать отзывы и ставить "
                "оценку произведениям (фильмам/книгам/песенкам), может комментировать чужие "
                "отзывы; может редактировать и удалять <b>свои</b> отзывы и комментарии. Эта роль "
                "присваивается по умолчанию каждому новому пользователю.</li>"
                "<li><b>Модератор</b> (<code>moderator</code>) — те же права, что и у "
                "<b>Аутентифицированного пользователя</b> плюс право удалять <b>любые</b> отзывы и "
                "комментарии.</li>"
                "<li><b>Администратор</b> (<code>admin</code>) — полные права на управление всем "
                "контентом проекта. Может создавать и удалять произведения, категории и жанры. "
                "Может назначать роли пользователям.</li>"
                "<li><b>Суперюзер Django</b> — обладет правами администратора (<code>admin</code>)"
                "</li></ul>"
            ),
        },
        {
            "name": "AUTH",
            "description": "Регистрация пользователей и выдача токенов",
        },
        {
            "name": "CATEGORIES",
            "description": "Категории (типы) произведений",
        },
        {
            "name": "GENRES",
            "description": "Категории жанров",
        },
        {
            "name": "TITLES",
            "description": (
                "Произведения, к которым пишут отзывы (определённый фильм, книга или песенка)."
            ),
        },
        {
            "name": "REVIEWS",
            "description": "Отзывы",
        },
        {
            "name": "COMMENTS",
            "description": "Комментарии к отзывам",
        },
        {
            "name": "USERS",
            "description": "Пользователи",
        },
    ],
}
